---@meta Event
---`Event` is a data type that represents listenable events. You aren't able to create your own listenable events using this data type.
---@class (exact) Event<T>
---Connect the given `callback` to the `Event`. When the `Event` is fired, `callback` will be ran. The `Event`'s parameters may be passed to `callback`, if there are any.
---@field Connect fun(self: Event, callback: T)
---Disconnect the given `callback` from the `Event`.
---@field Disconnect fun(self: Event, callback: T)