---@meta NPC
---`NPC` (non-player character) is a `DynamicInstance` similar to a `Player` but that can be controlled by code. Like `Player`s, it can walk and jump, and its body part colors can be customized.
---@class (exact) NPC: DynamicInstance
---Determines the `Instance` that the `NPC` should walk towards.
---@field MoveTarget Instance
---Determines the `Color` of the `NPC`'s head.
---@field HeadColor Color
---Determines the `Color` of the `NPC`'s torso.
---@field TorsoColor Color
---Determines the `Color` of the `NPC`'s left arm.
---@field LeftArmColor Color
---Determines the `Color` of the `NPC`'s right arm.
---@field RightArmColor Color
---Determines the `Color` of the `NPC`'s left leg.
---@field LeftLegColor Color
---Determines the `Color` of the `NPC`'s right leg.
---@field RightLegColor Color
---Determines whether or not the `NPC` is anchored.
---@field Anchored boolean
---Determines the current health of the `NPC`.
---@field Health number
---Determines the maximum `Health` the `NPC` can have.
---@field MaxHealth number
---Determines the ID of the shirt the `NPC` is wearing.
---
---@deprecated Presumably no longer works. Use `NPC:AddClothing` and `NPC:RemoveClothing` instead.
---@field ShirtID integer
---Determines the ID of the pants the `NPC` is wearing.
---
---@deprecated Presumably no longer works. Use `NPC:AddClothing` and `NPC:RemoveClothing` instead.
---@field PantsID integer
---Determines the ID of the face the `NPC` is wearing.
---@field FaceID integer
---Determines how fast the `NPC` walks.
---@field WalkSpeed number
---Determines the Y velocity applied to the `NPC` when it jumps.
---@field JumpPower number
---Determines the velocity of the `NPC`.
---@field Velocity Vector3
---Returns the remaining distance before the `NPC` reaches the end of its pathfind.
---@field NavDestinationDistance number
---Returns whether or not the `NPC` has reached the end of its pathfind.
---@field NavDestinationReached boolean
---Returns whether or not the `NPC` has a valid path to its set destination.
---@field NavDestinationValid boolean
---Returns true if the `NPC` is currently standing on the ground.
---@field Grounded boolean
---Fires when the `NPC` dies.
---@field Died Event<fun()>
---Undocumented.
---@field AddClothing fun(self: NPC, id: integer)
---Undocumented.
---@field RemoveClothing fun(self: NPC, id: integer)
---Undocumented.
---@field ClearClothing fun(self: NPC)
---Loads the given `userID`'s avatar on the `NPC`.
---@field LoadAppearance fun(self: NPC, userID: integer)
---Clears the `NPC`'s appearance. This will set its appearance to a gray avatar.
---@field ClearAppearance fun(self: NPC)
---Sets the destination for the `NPC`'s pathfind to `position`.
---@field SetNavDestination fun(self: NPC, position: Vector3)
---Respawns the `NPC`.
---@field Respawn fun(self: NPC)
---Makes the `NPC` jump.
---@field Jump fun(self: NPC)
---Equips the given `tool` on the `NPC`.
---@field EquipTool fun(self: NPC, tool: Tool)
---Drops the `Tool` currently equipped on the `NPC`.
---@field DropTool fun(self: NPC)