---@meta Seat
---`Seat`s are `Part`s the `Player` can sit on.
---@class (exact) Seat: Part
---The `Player` that is currently sitting in this `Seat`.
---@field Occupant Player?
---Fires when the `player` sits in the `Seat`.
---@field Sat Event<fun(player: Player)>
---Fires when the `player` leaves the `Seat`.
---@field Vacated Event<fun(player: Player)>