---@meta DynamicInstance
---`DynamicInstance` is the base class where all objects with a position, rotation and scale derive from.
---@class (exact) DynamicInstance: Instance
---Determines the position of the `DynamicInstance`.
---@field Position Vector3
---Determines the rotation of the `DynamicInstance` in euler angles.
---@field Rotation Vector3
---Determines the `Position` of the `DynamicInstance` relative to its `Parent`.
---@field LocalPosition Vector3
---Determines the `Rotation` of the `DynamicInstance` relative to its `Parent` in euler angles.
---@field LocalRotation Vector3
---Determines the size of the `DynamicInstance`.
---@field Size Vector3
---Determines the `Size` of the `DynamicInstance` relative to its `Parent`.
---@field LocalSize Vector3
---Returns the `Quaternion` of the `DynamicInstance`.
---@field Quaternion Quaternion
---Determines the `Quaternion` of the `DynamicInstance` relative to its `Parent`.
---@field LocalQuaternion Quaternion
---Returns the forward `Vector3` of the `DynamicInstance`.
---@field Forward Vector3
---Returns the up `Vector3` of the `DynamicInstance`.
---@field Up Vector3
---Returns the right vector of the `DynamicInstance`.
---@field Right Vector3
---Rotates the `DynamicInstance` so that its `Forward` looks at the given `target`.
---@field LookAt fun(self: DynamicInstance, target: Vector3, worldUp: Vector3)
---@field LookAt fun(self: DynamicInstance, target: Vector3)
---@field LookAt fun(self: DynamicInstance, target: DynamicInstance)
---Moves the transform in the direction and distance of `translation`.
---@field Translate fun(self: DynamicInstance, translation: Vector3)
---Rotates the `DynamicInstance` around a point.
---@field RotateAround fun(self: DynamicInstance, point: Vector3, axis: Vector3, angle: number)
---Rotates the `DynamicInstance` by the given `eulerAngles`.
---@field Rotate fun(self: DynamicInstance, eulerAngles: Vector3)
---Unknown.
---@field InverseTransformPoint fun(self: DynamicInstance, point: Vector3): Vector3
---Unknown.
---@field TransformPoint fun(self: DynamicInstance, point: Vector3): Vector3
---Unknown.
---@field InverseTransformDirection fun(self: DynamicInstance, direction: Vector3): Vector3
---Unknown.
---@field TransformDirection fun(self: DynamicInstance, direction: Vector3): Vector3
---Unknown.
---@field InverseTransformVector fun(self: DynamicInstance, vector: Vector3): Vector3
---Unknown.
---@field TransformVector fun(self: DynamicInstance, position: Vector3): Vector3