---@meta Player
---`Player` is the class of the `Player` and its character.
---@class (exact) Player: Instance
---Determines how long it takes between the `Player`'s death and respawn.
---@field RespawnTime number
---Determines the velocity of the `Player`.
---@field Velocity Vector3
---Determines the maximum `Health` the `Player` can have.
---@field MaxHealth number
---Determines the current health of the `Player`.
---@field Health number
---Determines how fast the `Player` walks.
---@field WalkSpeed number
---Determines how fast the `Player` sprints.
---@field SprintSpeed number
---Determines whether or not stamina drain is enabled for the `Player`.
---@field StaminaEnabled boolean
---Determines the `Player`'s amount of stamina.
---@field Stamina number
---Determines the maximum `Stamina` the `Player` can have.
---@field MaxStamina number
---The rate at which `Stamina` regenerates after being depleted for the `Player`.
---@field StaminaRegen number
---Determines how high the `Player`'s jump is.
---@field JumpPower number
---Determines the position of the `Player`.
---@field Position Vector3
---Determines the position of the `Player`.
---@field Rotation Vector3
---Determines the position of the `Player`.
---@field Size Vector3
---Determines the `Player`'s username `Color` in the chat.
---@field ChatColor Color
---Determines whether or not the `Player` can move.
---@field CanMove boolean
---Determines whether or not the `Player` is anchored. The idle animation still plays and this property does not reset on `Respawned`.
---@field Anchored boolean
---Determines the `Color` of the `Player`'s head.
---@field HeadColor Color
---Determines the `Color` of the `Player`'s torso.
---@field TorsoColor Color
---Determines the `Color` of the `Player`'s left arm.
---@field LeftArmColor Color
---Determines the `Color` of the `Player`'s right arm.
---@field RightArmColor Color
---Determines the `Color` of the `Player`'s left leg.
---@field LeftLegColor Color
---Determines the `Color` of the `Player`'s right leg.
---@field RightLegColor Color
---Determines the ID of the shirt the `Player` is wearing.
---@field ShirtID integer
---Determines the ID of the pants the `Player` is wearing.
---@field PantsID integer
---Determines the ID of the face the `Player` is wearing.
---@field FaceID integer
---Returns whether or not the `Player` is currently focused on an input.
---
---@deprecated Use `Input.IsInputFocused` instead.
---@field IsInputFocused boolean
---Returns the `Seat` the `Player` is currently sitting in.
---@field SittingIn Seat?
---Returns the forward `Vector3` of the `Player`.
---@field Forward Vector3
---Returns the right `Vector3` of the `Player`.
---@field Right Vector3
---Returns whether or not the `Player` is a Polytoria admin.
---@field IsAdmin boolean
---Returns whether or not the `Player` is the creator of the current place.
---@field IsCreator boolean
---Returns the `Player`'s user ID.
---@field UserID integer
---@field ["Backpack"] Backpack
---Fires when the `Player` sends a chat message.
---@field Chatted Event<fun(message: string, event: PlayerChatEvent)>
---Fires when the `Player` dies.
---@field Died Event<fun()>
---Fires when the `Player` respawns.
---@field Respawned Event<fun()>
---Undocumented.
---@field AddClothing fun(self: Player, id: integer)
---Undocumented.
---@field RemoveClothing fun(self: Player, id: integer)
---Undocumented.
---@field ClearClothing fun(self: Player)
---Drops the `Tool` the `Player` is currently holding.
---@field DropTools fun(self: Player)
---Kicks the `Player` from the server with an optional `Reason` parameter.
---@field Kick fun(self: Player, Reason: string?)
---Loads the given `userID`'s avatar on the `Player`.
---@field LoadAppearance fun(self: Player, userID: integer)
---Clears the `Player`'s appearance. This will set its appearance to a gray avatar.
---@field ClearAppearance fun(self: Player)
---Checks if the `Player` owns an item.
---
---The result is cached for 5 minutes. There is a limit of 30 requests that can be made per minute per server.
---@field OwnsItem fun(self: Player, assetID: integer, callback: fun(errorMessage: string, ownsItem: boolean))
---Resets the `Player`'s appearance to their original appearance.
---@field ResetAppearance fun(self: Player)
---Respawns the `Player`.
---@field Respawn fun(self: Player)
---Sits the `Player` in the given `seat`.
---@field Sit fun(self: Player, seat: Seat)
---Unsits the `Player`.
---@field Unsit fun(self: Player, addForce: boolean?)
---Rotates the `Player` so that its `Forward` looks at the given `target`.
---@field LookAt fun(self: Player, target: Vector3, worldUp: Vector3)
---@field LookAt fun(self: Player, target: Vector3)
---@field LookAt fun(self: Player, target: DynamicInstance)
---Moves the transform in the direction and distance of `translation`.
---@field Translate fun(self: Player, translation: Vector3)
---Rotates the `Player` around a point.
---@field RotateAround fun(self: Player, point: Vector3, axis: Vector3, angle: number)
---Rotates the `Player` by the given `eulerAngles`.
---@field Rotate fun(self: Player, eulerAngles: Vector3)
---Unknown.
---@field InverseTransformPoint fun(self: Player, point: Vector3): Vector3
---Unknown.
---@field TransformPoint fun(self: Player, point: Vector3): Vector3
---Unknown.
---@field InverseTransformDirection fun(self: Player, direction: Vector3): Vector3
---Unknown.
---@field TransformDirection fun(self: Player, direction: Vector3): Vector3
---Unknown.
---@field InverseTransformVector fun(self: Player, vector: Vector3): Vector3
---Unknown.
---@field TransformVector fun(self: Player, position: Vector3): Vector3