---@meta Players
---`Players` is the container class for all `Player`s.
---@class (exact) Players: Instance
---Determines whether or not collisions between players are enabled.
---@field PlayerCollisionEnabled boolean
---Returns the client's local `Player`.
---@field LocalPlayer Player
---Fires when a player joins the server.
---@field PlayerAdded Event<fun(player: Player)>
---Fires when a player leaves the server.
---@field PlayerRemoved Event<fun(player: Player)>
---Returns an array of all the `Player`s in the world.
---@field GetPlayers fun(): Player[]
---Attempts to find the first `Player` with the given `username`.
---@field GetPlayer fun(username: string): Player?
---Attempts to find the first `Player` with the given `userID`.
---@field GetPlayerByID fun(userID: integer): Player?